### ISSUE TITLE
Public endpoints (no access_token)

### ISSUE THREAD

**Issue by neight-allen** [turingschool-projects/census#130]
Is it possible with doorkeeper(hodor) to have endpoints that don't require an access_token? There are some apps (like briefcase) where I'd love to use Census as the source of truth, but we want employers who are not in census to be able to view student portfolios.

**Comment by JStans12** [comment]
This should be fine. Maybe we can give the briefcase app a unique token to keep the endpoints locked down.

**Comment by srt32** [comment]
I think the right solution here is to have the briefcase app create an app token and use that instead of using a token on behalf of a user. Feel free to reopen if that doesn't work
