### ISSUE TITLE
Format Validation Warning in app/models/invitation.rb

### ISSUE THREAD

**Issue by j-sm-n** [turingschool-projects/census#63]
[Security issue from Hakiri](https://hakiri.io/projects/26d903365dd617/stacks/90a60a36dfaf92/builds/fa5ea510784dc0/warnings/b8a8e92d8612a6): Insufficient validation for 'email' using /@/. Use \A and \z as anchors in app/models/invitation.rb

**Comment by srt32** [comment]
Looks like this issue was resolved in https://github.com/turingschool-projects/census/commit/068924ee66d50563613eba3f2155ef04d36b1a15
