### ISSUE TITLE
Root path on confirmation email

### ISSUE THREAD

**Issue by bcgoss** [turingschool-projects/census#72]
Check that the root path is https://login.turing.io in the confirmation emails.

**Comment by bcgoss** [comment]
Could be in action mailer config

**Comment by j-sm-n** [comment]
`https://login.turing.io` doesn't seem to be redirecting anymore, so I think this issue has been resolved. We can confirm with Jeff later tonight or tomorrow.

**Comment by srt32** [comment]
This issue was fixed via an env var. Closing.
